PRICE_RATE_PER_KM = {
    'TOWN': 5,
    'CITY': 5.5,
    'METRO_CITY': 8
}

PRICE_ESTIMATION_DECREMENT_PERCENTAGE_FOR_PREMIUM_RIDERS = 5
PRICE_ESTIMATION_INCREMENT_PERCENTAGE_FOR_PREMIUM_DRIVERS = 10

MINIMUM_COUNT_OF_DRIVERS_TO_BE_DISCOVERED_FOR_DRIVER_FILTER_APPLICATION = 10
MAXIMUM_COUNT_OF_DRIVERS_IN_QUADTREE_NODE_LEAF = 5
