from enum import Enum


class GroupExpenseDistributionStrategies(Enum):
    GROUP_EXPENSE_DISTRIBUTION_STRATEGY_EQUAL = 'GROUP_EXPENSE_DISTRIBUTION_STRATEGY_EQUAL'
    GROUP_EXPENSE_DISTRIBUTION_STRATEGY_PERCENTAGE = 'GROUP_EXPENSE_DISTRIBUTION_STRATEGY_PERCENTAGE'
