# Generated by Django 5.0.6 on 2024-05-21 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0003_region'),
        ('property', '0002_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available_from', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available_for_booking', models.BooleanField(default=False)),
                ('booking_id', models.PositiveIntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_city', to='geo.city')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.property')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_region', to='geo.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='geo.state')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city', 'region', 'available_from'], name='listing_lis_state_i_e7e3cc_idx')],
            },
        ),
    ]
