# Generated by Django 5.0.6 on 2024-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_region'),
        ('listing', '0001_initial'),
        ('property', '0003_rename_id_property_property_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_lis_state_i_e7e3cc_idx',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='booking_id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available_for_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['state', 'city', 'region', 'available_from', 'price'], name='listing_lis_state_i_63ccdd_idx'),
        ),
    ]
