# Generated by Django 5.0.6 on 2024-05-27 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0002_remove_listing_listing_lis_state_i_e7e3cc_idx_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_start_datetime', models.DateTimeField()),
                ('booking_duration_in_days', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(limit_value=1))),
                ('booking_end_datetime', models.DateTimeField()),
                ('booking_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('EXPIRED', 'BOOKING_EXPIRED')], max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_listing', to='listing.listing')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='payment.payment')),
            ],
        ),
    ]
