from enum import Enum


class ParkingSpotType(Enum):

    TWO_WHEELER_PARKING_SPOT = 'TWO_WHEELER_PARKING_SPOT'
    COMPACT_CAR_PARKING_SPOT = 'COMPACT_CAR_PARKING_SPOT'
    LARGE_CAR_PARKING_SPOT = 'LARGE_CAR_PARKING_SPOT'
