# Generated by Django 5.0.6 on 2024-05-15 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(editable=False, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)])),
                ('longitude', models.FloatField(editable=False, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)])),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('images_url', models.URLField(default='', max_length=500)),
            ],
        ),
    ]
