# Generated by Django 5.0.6 on 2024-05-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='id',
            new_name='property_id',
        ),
    ]
