from enum import Enum


class SearchEngineType(Enum):
    SEARCH_ENGINE_DB_SEARCH_LISTING_ENGINE = 'SEARCH_ENGINE_DB_SEARCH_LISTING_ENGINE'
    SEARCH_ENGINE_QUADTREE_SEARCH_LISTING_ENGINE = 'SEARCH_ENGINE_QUADTREE_SEARCH_LISTING_ENGINE'
